export const LOGIN = 'user/login'
export const REGISTER = 'user/register'
export const SECURED = 'user/validate-token'
export const CREATE_TODO = 'todo/create'
export const GET_TODO = 'todo/get'
export const UPDATE_STATE = 'todo/'
